a = input('Digite algo:')
print('O tipo primitivo disso é {}.'.format(type(a)))
print('Só tem espaços? {}'.format(a.isspace()))
print('É um número? {}'.format(a.isnumeric()))
print('É alfanumérico? {}'.format(a.isalnum()))
print('É alfabético? {}'.format(a.isalpha()))
print('Está em maiúsculas? {}'.format(a.isupper()))
print('Está em minúsculas? {}'.format(a.islower()))
print('Está capitalizada? {}'.format(a.istitle()))
